### ISSUE TITLE
Problem tryng to instal imGUI-Odin on OpenSuse Tumbleweed. 

### ISSUE THREAD

**Issue by joaocarvalhoopen** [foxik0169/imgui-odin#1]
Hello,
good morning,
I'm trying to install imgui-odin in openSuse tumbleweed, i cloned the repository, I intalled libjit, I installed freetype package and freetype-dev package, I installed cmake.

But when I run the ./build.sh command it give me the following error and I tryed everythong but it doesn't correct this erros and doesn't end the compilation.

I have configured freetype_DIR in ``` ~/.bashrc ``

export freetype_DIR=/usr/local/lib64

But it still doesn't work and doesn't find the freetype path.

```
CMake Error at CMakeLists.txt:30 (FIND_PACKAGE):
  Could not find a package configuration file provided by "freetype" with any
  of the following names:

    freetypeConfig.cmake
    freetype-config.cmake

  Add the installation prefix of "freetype" to CMAKE_PREFIX_PATH or set
  "freetype_DIR" to a directory containing one of the above files.  If
  "freetype" provides a separate development package or SDK, be sure it has
  been installed.

```

Thank you very much,

Best regards,
Joao Carvalho

**Comment by foxik0169** [comment]
This is out of scope of this project. I am sorry but I can not help you with your local setup. The cmake script is the original one from cimgui. If you don't need Freetype you can disable it in the build.sh script. Otherwise, CMake must be able to find freetype in your system for it to be able to generate configuration.

Daniel
